monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        profiler:
            type: fingers_crossed
            action_level: error
            handler: nested
            buffer_size: 50

        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        deprecation:
            type: stream
            path: "%kernel.logs_dir%/deprecations.log"
            level: info
            channels: ["php"]
